import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, CalendarDays, Check, ChevronDown, Clock3, HeartPulse, Mail, Menu, MessageCircle, Play, ShieldCheck, Sparkles, Stethoscope, X, Zap } from 'lucide-react'
import { motion, useMotionValue, useScroll, useSpring, useTransform } from 'framer-motion'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import './styles.css'
import './form.css'
import './redesign.css'
import './motion.css'
import './hero.css'
import './premium.css'
import './story.css'

const agents = [
  { name: 'Front Desk Agent', desc: 'Books, reschedules, confirms and answers — with warmth that feels entirely human.', icon: CalendarDays, tint: 'blue' },
  { name: 'Clinical Scribe', desc: 'Turns every conversation into structured notes, summaries and next steps automatically.', icon: Stethoscope, tint: 'teal' },
  { name: 'Care Coordinator', desc: 'Closes the loop on referrals, reminders and patient follow-ups before they become gaps.', icon: HeartPulse, tint: 'pink' },
]

function Header() {
  const [open, setOpen] = useState(false)
  return <header className="wrap header"><a href="#top" className="brand"><span className="brandMark"><HeartPulse size={18}/></span>mykare ai</a><nav className={open ? 'nav mobileOpen' : 'nav'}><a href="#agents" onClick={() => setOpen(false)}>Platform</a><a href="#workflow" onClick={() => setOpen(false)}>Workflow</a><a href="#integrations" onClick={() => setOpen(false)}>Integrations</a><a href="#pricing" onClick={() => setOpen(false)}>Pricing</a></nav><div className="headerActions"><a className="login" href="#contact">Sign in</a><a className="topCta" href="#contact">Book a demo</a><button className="menuBtn" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X size={20}/> : <Menu size={20}/>}</button></div></header>
}

function Dashboard() {
  const ref = useRef(null)
  const [tilt, setTilt] = useState({ x: 48, z: -6 })
  const move = e => { const r = ref.current.getBoundingClientRect(); setTilt({ x: 48 - ((e.clientY-r.top)/r.height-.5)*8, z: -6 + ((e.clientX-r.left)/r.width-.5)*5 }) }
  return <div className="heroArt" onMouseMove={move} onMouseLeave={() => setTilt({x:48,z:-6})}>
    <div className="orb orbOne"/><div className="orb orbTwo"/><div className="orb orbThree"/>
    <div className="floatingIcon iconOne"><ShieldCheck size={19}/></div><div className="floatingIcon iconTwo"><Zap size={19}/></div><div className="floatingIcon iconThree"><Sparkles size={19}/></div>
    <motion.div className="dashboard" ref={ref} initial={{ opacity: 0, y: 20, scale: .94 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ delay: .45, duration: 1.1, ease: [.2,.7,.2,1] }} style={{ transform: `translateX(-50%) perspective(1000px) rotateX(${tilt.x}deg) rotateZ(${tilt.z}deg)` }}>
      <div className="dashTop"><span className="dots"><i/><i/><i/></span><b>mykare / command center</b><span>•••</span></div>
      <div className="dashBody"><aside><i className="sideActive"/><i/><i className="short"/><i/><i className="short"/></aside><div className="chartArea"><div className="miniRow"><Mini title="Patients" value="2,418"/><Mini title="Wait time" value="12m"/><Mini title="Resolved" value="94%" green/></div><div className="chart"><svg viewBox="0 0 420 110" preserveAspectRatio="none"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#5977f4"/><stop offset="1" stopColor="#fff" stopOpacity="0"/></linearGradient></defs><path d="M0 81 C30 78 36 52 64 63 S99 90 130 63 S166 18 202 53 S234 78 267 42 S302 25 340 47 S380 18 420 27" fill="none" stroke="#627bf1" strokeWidth="3"/><path d="M0 81 C30 78 36 52 64 63 S99 90 130 63 S166 18 202 53 S234 78 267 42 S302 25 340 47 S380 18 420 27 V110 H0Z" fill="url(#chartFill)" opacity=".17"/></svg></div></div></div>
    </motion.div><div className="agentPill">● AI agent active <b>• live</b></div><div className="spark s1">✦</div><div className="spark s2">✧</div>
  </div>
}
function Mini({title,value,green}) { return <div className="mini"><small>{title}</small><strong className={green?'green':''}>{value}</strong></div> }
function SectionHead({label,title,sub}) { return <><div className="sectionLabel">{label}</div><h2 className="sectionTitle" dangerouslySetInnerHTML={{__html:title}}/>{sub && <p className="sectionSub">{sub}</p>}</> }
function Network() { return <div className="network"><svg viewBox="0 0 900 360" preserveAspectRatio="none"><path d="M450 180 L210 105 M450 180 L700 112 M450 180 L240 286 M450 180 L674 279" stroke="#bdc9f1" strokeWidth="1.5" strokeDasharray="5 7"/><circle cx="450" cy="180" r="120" fill="none" stroke="#dce4ff" strokeDasharray="3 8"/></svg><Node cls="centerNode" text={<>MYKARE<br/>CORE</>}/><Node cls="n1" text={<>FRONT<br/>DESK</>}/><Node cls="n2" text={<>CLINICAL<br/>AI</>}/><Node cls="n3" text={<>BILLING<br/>AI</>}/><Node cls="n4" text={<>CARE<br/>AI</>}/><span className="nodeLabel label1">Patient access</span><span className="nodeLabel label2">Clinical intelligence</span><span className="nodeLabel label3">Revenue cycle</span><span className="nodeLabel label4">Continuity of care</span></div> }
function Node({cls,text}) { return <div className={`node ${cls}`}>{text}</div> }
function DashboardPreview() { return <div className="productScreen"><div className="liveTop"><span>● LIVE DASHBOARD</span><b>Tuesday, 24 Sep 2024</b></div><div className="screenGrid"><div className="screenCard"><small>ACTIVE PATIENTS</small><strong>2,418</strong><em>↑ 12.4% this month</em></div><div className="screenCard"><small>AVG. RESPONSE TIME</small><strong>12m</strong><em>↓ 4m from last week</em></div><div className="screenCard wide"><small>CARE OPERATIONS / 30 DAYS</small><div className="barChart">{[35,48,43,66,55,76,68,88,77,94,82,100].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div></div></div> }
function FAQ() { const [active,setActive]=useState(0); const qs=['What is Mykare AI?','Will it work with our existing systems?','How do you handle patient data?','How quickly can we get started?']; const as=['Mykare is the AI-native operating system for healthcare — a connected layer of intelligent agents that helps teams automate operations and deliver more human care.','Yes. Mykare is designed to fit into the systems your team already uses through secure, flexible integrations.','Security, privacy and responsible AI are built into every layer. Talk to our team for details on compliance and your specific workflow.','Most teams are up and running in weeks, not months. We will map your first workflow together and expand from there.']; return <div className="faqList">{qs.map((q,i)=><div className={`faqItem ${active===i?'open':''}`} key={q}><button className="faqQ" onClick={()=>setActive(active===i?-1:i)}>{q}<ChevronDown size={18}/></button><div className="faqA">{as[i]}</div></div>)}</div> }
function Magnetic({ children, className }) { const x = useMotionValue(0); const y = useMotionValue(0); const sx = useSpring(x, { stiffness: 280, damping: 18 }); const sy = useSpring(y, { stiffness: 280, damping: 18 }); return <motion.a className={className} href="#contact" style={{ x: sx, y: sy }} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.2);y.set((e.clientY-r.top-r.height/2)*.2)}} onMouseLeave={()=>{x.set(0);y.set(0)}}>{children}</motion.a> }
function MedicalCore() { return <motion.div className="medicalCore" animate={{ y:[0,-10,0], rotate:[0,2,-1,0] }} transition={{ duration:8, repeat:Infinity, ease:'easeInOut' }}><div className="coreHalo"/><svg viewBox="0 0 220 220" fill="none" aria-label="3D medical AI illustration"><defs><linearGradient id="coreGradient" x1="30" y1="20" x2="190" y2="200"><stop stopColor="#dbe8ff"/><stop offset=".48" stopColor="#6d83ff"/><stop offset="1" stopColor="#8d5ee5"/></linearGradient><radialGradient id="coreLight"><stop stopColor="#fff" stopOpacity=".9"/><stop offset="1" stopColor="#fff" stopOpacity="0"/></radialGradient></defs><ellipse cx="110" cy="188" rx="64" ry="14" fill="#5266c8" opacity=".12"/><path d="M110 18c35 0 65 18 78 45 16 32 3 78-21 103-16 17-35 29-57 34-26-3-51-16-66-35-23-29-29-72-11-104 14-25 42-43 77-43Z" fill="url(#coreGradient)" opacity=".94"/><path d="M110 28c27 0 51 13 62 34 13 24 4 59-14 78-12 13-28 21-48 26-18-3-36-13-47-28-17-23-21-53-8-76 11-20 31-34 55-34Z" fill="#eef3ff" opacity=".25"/><ellipse cx="78" cy="69" rx="41" ry="26" fill="url(#coreLight)" opacity=".45"/><path d="M110 62v67M80 96h60" stroke="white" strokeWidth="9" strokeLinecap="round"/><path d="M110 62v67M80 96h60" stroke="#fff" strokeWidth="3" strokeLinecap="round"/><circle cx="110" cy="96" r="13" fill="#fff" fillOpacity=".24" stroke="#fff" strokeWidth="2"/><path d="M109 89v14M102 96h14" stroke="white" strokeWidth="2" strokeLinecap="round"/></svg><span className="coreLabel">MYKARE / CORE</span></motion.div> }
function AgentCard({icon:Icon,label,status,onClick}) { return <motion.button className="floatingAgent" whileHover={{ y:-7, scale:1.03 }} whileTap={{ scale:.97 }} onClick={onClick}><span className="agentGlyph"><Icon size={16}/></span><span><b>{label}</b><small><i/> {status}</small></span><ArrowRight size={13}/></motion.button> }
function Hero() { const [active,setActive]=useState('Care Coordinator'); return <section className="hero fullHero"><div className="heroLight lightA"/><div className="heroLight lightB"/><div className="heroCopy"><motion.div className="eyebrow" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7}}>The intelligence layer for care</motion.div><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:1,delay:.12,ease:[.2,.7,.2,1]}}>Healthcare,<br/><span>reimagined by AI.</span></motion.h1><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7,delay:.25}}>The AI-native operating system that gives your team more time to care, and every patient a better experience.</motion.p><motion.div className="heroActions" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.7,delay:.38}}><Magnetic className="primary">Join the waitlist <ArrowRight size={15}/></Magnetic><Magnetic className="secondary">Book a demo</Magnetic><a className="watch" href="#workflow"><i><Play size={11} fill="currentColor"/></i> Watch demo</a></motion.div></div><div className="heroStage"><div className="stageRing ringOne"/><div className="stageRing ringTwo"/><MedicalCore/><Dashboard/><div className="stageAgent agentA"><AgentCard icon={CalendarDays} label="Front Desk" status={active==='Front Desk'?'active':'ready'} onClick={()=>setActive('Front Desk')}/></div><div className="stageAgent agentB"><AgentCard icon={Stethoscope} label="Clinical Scribe" status={active==='Clinical Scribe'?'active':'ready'} onClick={()=>setActive('Clinical Scribe')}/></div><div className="stageAgent agentC"><AgentCard icon={HeartPulse} label="Care Coordinator" status={active==='Care Coordinator'?'active':'ready'} onClick={()=>setActive('Care Coordinator')}/></div><div className="activeTrace"><span className="tracePulse"/> {active} is {active==='Care Coordinator'?'closing the loop':'standing by'}</div></div><motion.a className="scrollCue" href="#agents" animate={{ y:[0,7,0] }} transition={{ duration:1.8, repeat:Infinity, ease:'easeInOut' }}><span>Scroll to explore</span><i/></motion.a></section> }
function App() {
  const [submitted,setSubmitted]=useState(false); const [sending,setSending]=useState(false); const [error,setError]=useState(''); const [booting,setBooting]=useState(true)
  const { scrollYProgress } = useScroll()
  const smoothScroll = useSpring(scrollYProgress, { stiffness: 80, damping: 22, mass: .25 })
  const blobY = useTransform(smoothScroll, [0, 1], ['0%', '36%'])
  useEffect(() => {
    gsap.registerPlugin(ScrollTrigger)
    const root = document.documentElement
    const onMove = e => { root.style.setProperty('--mouse-x', `${e.clientX}px`); root.style.setProperty('--mouse-y', `${e.clientY}px`); root.style.setProperty('--spot-x', `${e.clientX - 180}px`); root.style.setProperty('--spot-y', `${e.clientY - 180}px`) }
    window.addEventListener('pointermove', onMove)
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('isVisible') }), { threshold: .12 })
    document.querySelectorAll('.reveal').forEach(el => observer.observe(el))
    const ctx = gsap.context(() => {
      gsap.utils.toArray('.gsap-reveal').forEach((el, i) => gsap.fromTo(el, { y: 48, opacity: 0 }, { y: 0, opacity: 1, duration: .95, delay: i * .04, ease: 'power3.out', scrollTrigger: { trigger: el, start: 'top 86%', once: true } }))
      gsap.utils.toArray('.counter').forEach(el => { const target = parseFloat(el.dataset.target || '0'); const suffix = el.dataset.suffix || ''; gsap.fromTo(el, { innerText: 0 }, { innerText: target, duration: 1.6, ease: 'power2.out', snap: { innerText: target % 1 ? .1 : 1 }, scrollTrigger: { trigger: el, start: 'top 88%', once: true }, onUpdate: () => { el.textContent = `${target % 1 ? Number(el.innerText).toFixed(1) : Math.round(Number(el.innerText))}${suffix}` } }) })
    })
    const bootTimer = setTimeout(() => setBooting(false), 900)
    return () => { window.removeEventListener('pointermove', onMove); observer.disconnect(); ctx.revert(); clearTimeout(bootTimer) }
  }, [])
  return <><motion.div className="bootScreen" initial={{opacity:1}} animate={{opacity:booting?1:0,pointerEvents:booting?'auto':'none'}} transition={{duration:.45}}><div className="bootMark"><HeartPulse size={22}/></div><span>mykare ai</span><i><b/></i></motion.div><StoryProgress/><div className="cursorSpotlight"/><motion.div className="mouseGlow" style={{ y: blobY }}/><div className="ambient"><motion.div className="gridBg" style={{ y: blobY }}/><Particles/></div><Header/><main id="top">
    <Hero/>
    <div className="logoStrip"><div className="logoRow">{['apollo','NovaCare','Wellspace','MedAxis','Cura','apollo','NovaCare','Wellspace','MedAxis','Cura'].map((x,i)=><span key={i}><b className={`logoDot d${i%4}`}/>{x}</span>)}</div></div>
    <section className="wrap section reveal"><div className="split"><div className="sectionCopy"><SectionHead label="The status quo" title={'Care should feel human. <span>Operations shouldn\'t.</span>'} sub="Healthcare teams lose thousands of hours to repetitive administrative work. Mykare gives that time back — so people can focus on people."/></div><div className="statStack"><Stat n="62%" title="of a clinician's day is admin" text="Documentation, scheduling, follow-ups and data entry take care away from care."/><Stat n="3.2×" title="more demand, same capacity" text="Patient expectations are rising while teams are stretched thinner than ever."/></div></div></section>
    <section className="solution" id="agents"><div className="wrap center reveal"><SectionHead label="One intelligent layer" title={'Meet your new<br/><span>care team.</span>'} sub="A fleet of specialised AI agents that work together, learn your workflows, and amplify your team — around the clock."/><div className="agentGrid">{agents.map(({name,desc,icon:Icon,tint})=><div className="featureCard" key={name}><div className={`agentIcon ${tint}`}><Icon size={20}/></div><h3>{name}</h3><p>{desc}</p></div>)}</div><Network/></div></section>
    <section id="workflow" className="wrap section reveal"><div className="productLayout"><div className="sectionCopy"><SectionHead label="A single source of truth" title={'See the whole picture. <span>In real time.</span>'} sub="Mykare turns scattered signals into one calm, clear command center for your entire operation."/><a className="primary inline" href="#contact">Explore the platform <ArrowRight size={15}/></a></div><DashboardPreview/></div><div className="timeline">{[['01','Listen','Every patient signal, captured in context.'],['02','Understand','AI makes sense of the details that matter.'],['03','Act','Agents take the next best action, instantly.'],['04','Learn','Your system gets smarter with every interaction.']].map(([n,t,d])=><div className="step" key={n}><div className="stepNum">{n}</div><h3>{t}</h3><p>{d}</p></div>)}</div></section>
    <section className="wrap center section reveal"><SectionHead label="Built for better outcomes" title={'More time for care.<br/><span>More care for everyone.</span>'}/><div className="metrics"><Metric n="40%" text="less time spent on repetitive admin"/><Metric n="2.4×" text="faster patient response times"/><Metric n="24/7" text="always-on operational intelligence"/></div></section>
    <section className="darkBand" id="integrations"><div className="wrap center reveal"><SectionHead label="Plays well with your stack" title={'Your tools.<br/><strong>One intelligent layer.</strong>'} sub="Mykare connects to the systems you already trust, so your team can keep moving without changing how they work."/><div className="integrations">{['◉ Epic','✦ Salesforce','◎ Athenahealth','◈ HubSpot','⌁ Twilio','◌ Stripe'].map(x=><span key={x}>{x}</span>)}</div></div></section>
    <Pricing/><section className="wrap section center reveal"><SectionHead label="What teams are saying" title={'Care leaders are<br/><span>thinking bigger.</span>'}/><div className="quotes">{[['“Mykare gave our team back 18 hours every week. But the real win is that patients feel the difference.”','AR','Dr. Anika Rao','Medical Director, NovaCare'],['“It feels less like a software tool and more like a brilliant colleague who never clocks out.”','JM','James Mitchell','COO, Wellspace Health'],['“The calm it brings to our operations is hard to put a number on. Everyone has more room to care.”','SL','Sarah Lee','VP Operations, Cura']].map(([q,initial,name,role])=><div className="quote" key={name}><p>{q}</p><small><b>{initial}</b><span><strong>{name}</strong><br/>{role}</span></small></div>)}</div></section>
    <section className="wrap section reveal"><div className="center"><SectionHead label="Questions, answered" title={'Good things should<br/><span>feel clear.</span>'}/></div><FAQ/></section>
    <section className="contact" id="contact"><div className="wrap"><div className="contactBox reveal"><SectionHead label="The future of care is closer than you think" title={'Ready to make room<br/>for <span>what matters?</span>'} sub="Send us a message and our team will get back to you."/><form className="contactForm" onSubmit={async e=>{e.preventDefault();setSending(true);setError('');try{const form=new FormData(e.currentTarget);const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.get('name'),email:form.get('email'),message:form.get('message')})});const body=await response.text();let result={};try{result=body?JSON.parse(body):{}}catch{throw new Error(`Server returned an invalid response (${response.status}).`)}if(!response.ok) throw new Error(result.message||'Unable to send right now.');setSubmitted(true)}catch(err){setError(err.message||'Unable to send right now.')}finally{setSending(false)}}}>{submitted ? <p className="success"><Check size={15}/> Message sent successfully — we’ll be in touch soon.</p> : <><div className="formRow"><input name="name" placeholder="Your name" required/><input name="email" type="email" placeholder="Work email address" required/></div><textarea name="message" placeholder="How can we help?" rows="4" required></textarea><button className="primary" disabled={sending}>{sending?'Sending…':<>Send message <ArrowRight size={15}/></>}</button>{error&&<small className="formError">{error}</small>}</>}</form></div></div></section>
  </main><footer className="wrap footer"><a href="#top" className="brand"><span className="brandMark"><HeartPulse size={15}/></span>mykare ai</a><span>© 2024 Mykare AI. Built for better care.</span><nav><a href="#">Privacy</a><a href="#">Terms</a><a href="#contact">Contact</a></nav></footer></>
}
function Stat({n,title,text}){return <div className="stat"><strong>{n}</strong><div><h3>{title}</h3><p>{text}</p></div></div>};function Metric({n,text}){const value=n.replace(/[^\d.]/g,'');const suffix=n.replace(/[\d.]/g,'');return <div className="metric gsap-reveal"><strong className="counter" data-target={value} data-suffix={suffix}>0{suffix}</strong><p>{text}</p></div>}
function Particles(){return <div className="particles" aria-hidden="true">{Array.from({length:26},(_,i)=><motion.i key={i} style={{left:`${(i*37)%100}%`,top:`${(i*61)%100}%`}} animate={{y:[0,-18,0],x:[0,i%2?10:-10,0],opacity:[.15,.65,.15],scale:[.7,1,.7]}} transition={{duration:4+(i%5),repeat:Infinity,delay:i*.15,ease:'easeInOut'}}/>)}</div>}
function StoryProgress(){const {scrollYProgress}=useScroll();return <motion.div className="storyProgress" style={{scaleX:scrollYProgress}}/>}
function Pricing(){return <section id="pricing" className="wrap section center reveal"><SectionHead label="Simple, transparent pricing" title={'Start small.<br/><span>Scale with confidence.</span>'}/><div className="pricing">{[['Essentials','$499','For focused teams building a more efficient front desk.'],['Growth','$1,499','For growing clinics ready to transform operations.'],['Enterprise','Let\'s talk','For health systems with complex needs and ambitious goals.']].map(([name,price,desc],i)=><div className={`priceCard ${i===1?'featured':''}`} key={name}>{i===1&&<em>MOST POPULAR</em>}<h3>{name}</h3><strong>{price}<small>{i<2&&'/mo'}</small></strong><p>{desc}</p><ul>{['Full agent suite','Up to 10,000 conversations','Advanced analytics'].map((x,j)=><li key={x}><Check size={13}/>{i===0?['1 AI agent','Up to 2,000 conversations','Core integrations'][j]:i===2?['Custom agent workflows','Unlimited conversations','Dedicated success team'][j]:x}</li>)}</ul><a className={i===1?'primary':'secondary'} href="#contact">{i===2?'Talk to sales':i===1?'Book a demo':'Get started'}</a></div>)}</div></section>}

createRoot(document.getElementById('root')).render(<App />)
